### PR TITLE
Build Main Features

### PR DESCRIPTION
**Pull request by Xanonymous-GitHub**

### CODE REVIEW

**Comment by Xanonymous-GitHub** [comment]
Create Main Todo Card Object in main area.

**Comment by Xanonymous-GitHub** [comment]
- [ ] when no item can be see, the main-content component should have  a background image.

**Comment by Xanonymous-GitHub** [comment]
main content doesn't work

**Comment by Xanonymous-GitHub** [comment]
- [ ] add item button

- [ ] editor dialog

**Comment by txya900619** [comment]
you don't 勾勾 any one

**Comment by txya900619** [comment]
What is gb

**Comment by Xanonymous-GitHub** [comment]
when item be deleted, it still show on the finished or unfinished page :)

**Comment by Xanonymous-GitHub** [comment]
bg shows at the wrong time

**Comment by Xanonymous-GitHub** [comment]
EditorDialog and Features:"add item".

**Comment by Xanonymous-GitHub** [comment]
Screenshot from 2019-12-30 03-43-36

**Comment by Xanonymous-GitHub** [comment]
Features:"edit item"

**Comment by Xanonymous-GitHub** [comment]
Screenshot from 2020-01-02 02-42-32

**Pull request merged**
